{% set name = "nannyml" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nannyml-{{ version }}.tar.gz
  sha256: d32fa3bec8e4c654d941fc597dbf379a390c3640d0ca0cf1a1acdefd397a228b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.1,<3.11
  run:
    - category_encoders >=2.3.0,<3.0.0
    - gcsfs >=2022.5.0
    - joblib >=1.1.0,<2.0.0
    - matplotlib-base >=3.5.1,<4.0.0
    - numpy <1.23.0,>=1.16.5
    - offset >=0.0.2,<0.0.3
    - pandas >=1.3.0,<2.0.0
    - plotly >=5.6.0,<6.0.0
    - pyarrow >=8.0.0
    - python >=3.7.1,<3.11
    - python-dateutil >=2.8.2,<3.0.0
    - python-kaleido ==0.2.1
    - scikit-learn >=1.0.2,<2.0.0
    - scipy ~=1.7.3
    - seaborn >=0.11.2,<0.12.0
    - types-python-dateutil >=2.8.9,<3.0.0

test:
  imports:
    - nannyml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nannyml/nannyml
  doc_url: https://nannyml.readthedocs.io/en/stable/
  summary: NannyML, Your library for monitoring model performance.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
