{% set name = "nannyml" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nannyml-{{ version }}.tar.gz
  sha256: 809e8e60373bc80365b3490488d90bed3f9c498ba6ceb80b8467a9af8afcf413

build:
  entry_points:
    - nannyml=nannyml.cli.cli:cli
    - nml=nannyml.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.23
    - scipy >=1.9.2
    - pandas >=1.4
    - scikit-learn >=1.3
    - pyarrow >=13.0
    - python-dateutil >=2.8.0,<3.0.0
    - joblib >=1.1.0,<2.0.0
    - category_encoders >=2.3.0,<3.0.0
    - matplotlib-base >=3.7.0,<4.0.0
    - plotly >=5.6.0,<6.0.0
    - seaborn >=0.13.0,<0.14.0
    - python-kaleido >=0.2.0,<0.3.0
    - gcsfs >=2022.5
    - pydantic >=2.7
    - rich >=12.5
    - click >=8.1.0,<9.0.0
    - pyyaml >=6.0.0,<7.0.0
    - jinja2 <3.1
    - pyfiglet >=0.8.0.post1,<0.9.0
    - lightgbm >=3.3,<4.6
    - flaml >=2.3.3,<3.0.0
    - s3fs >=2022.8
    - apscheduler >=3.9.0,<4.0.0
    - analytics-python >=2.3.0,<3.0.0
    - python-dotenv >=1.0,<2.0
    # From flaml[automl]
    - lightgbm >=2.3.1
    - xgboost >=0.90,<3.0.0

test:
  imports:
    - nannyml
  commands:
    - pip check
    - nannyml --help
    - nml --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nannyml/nannyml
  doc_url: https://nannyml.readthedocs.io/en/stable/
  summary: NannyML, Your library for monitoring model performance.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nnansters
    - thewchan
