{% set name = "nannyml" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nannyml-{{ version }}.tar.gz
  sha256: 0e52fed76d92169b211744844059e57d921684e2570add4c57fc1c699a75da66

build:
  entry_points:
    - nannyml=nannyml.cli.cli:cli
    - nml=nannyml.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.1,<3.11
  run:
    - category_encoders >=2.3.0,<3.0.0
    - click >=8.1.3,<9.0.0
    - flaml >=1.0.11,<2.0.0
    - gcsfs >=2022.5.0,<2023.0.0
    - jinja2 <3.1
    - joblib >=1.1.0,<2.0.0
    - lightgbm  >=3.3.2,<4.0.0
    - matplotlib-base >=3.5.1,<4.0.0
    - numpy >=1.21,<2.0
    - pandas >=1.3.0,<2.0
    - plotly >=5.6.0,<6.0.0
    - pyarrow <9.0.0,>=8.0.0
    - pydantic >=1.9.1,<2.0.0
    - pyfiglet >=0.8.post1,<0.9
    - python >=3.7.1,<3.11
    - python-dateutil >=2.8.2,<3.0.0
    - python-kaleido ==0.2.1
    - pyyaml >=6.0,<7.0
    - rich >=12.5.1,<13.0.0
    - scikit-learn >=1.0.2,<2.0.0
    - scipy >=1.7.3,<2.0.0
    - seaborn >=0.11.2,<0.12.0

test:
  imports:
    - nannyml
    - nannyml.cli
    - nannyml.datasets
    - nannyml.datasets.data
    - nannyml.drift
    - nannyml.drift.model_inputs
    - nannyml.drift.model_inputs.multivariate
    - nannyml.drift.model_inputs.multivariate.data_reconstruction
    - nannyml.drift.model_inputs.univariate
    - nannyml.drift.model_inputs.univariate.statistical
    - nannyml.drift.model_outputs
    - nannyml.drift.model_outputs.univariate
    - nannyml.drift.model_outputs.univariate.statistical
    - nannyml.drift.target
    - nannyml.drift.target.target_distribution
    - nannyml.io
    - nannyml.performance_calculation
    - nannyml.performance_calculation.metrics
    - nannyml.performance_estimation
    - nannyml.performance_estimation.confidence_based
    - nannyml.performance_estimation.direct_loss_estimation
    - nannyml.plots
    - nannyml.sampling_error
  commands:
    - pip check
    - nannyml --help
    - nml --help
  requires:
    - pip

about:
  home: https://github.com/nannyml/nannyml
  doc_url: https://nannyml.readthedocs.io/en/stable/
  summary: NannyML, Your library for monitoring model performance.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nnansters
    - thewchan
