{% set name = "nannyml" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nannyml-{{ version }}.tar.gz
  sha256: db0e4a688d9d830ad3c461106f42335588ee03241f16a00fde00767b408ef704

build:
  entry_points:
    - nannyml=nannyml.cli.cli:cli
    - nml=nannyml.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9,<3.12
  run:
    - python >=3.9,<3.12
    - pandas >=1.5.0,<2.0
    - python-dateutil >=2.8.2,<3.0.0
    - scikit-learn >=1.2,<2.0.0
    - joblib >=1.1.0,<2.0.0
    - category_encoders >=2.3.0,<3.0.0
    - matplotlib-base >=3.7,<4.0.0
    - plotly >=5.6.0,<6.0
    - scipy >=1.10,<2.0.0
    - numpy >=1.24,<1.25
    - seaborn >=0.13.2,<0.14.0
    - python-kaleido ==0.2.1
    - pyarrow <15.0.0,>=14.0.0
    - gcsfs >=2022.5.0,<2023.0.0
    - pydantic >=2.7.4,<3.0.0
    - rich >=12.5.1,<13.0.0
    - click >=8.1.3,<9.0.0
    - pyyaml >=6.0,<7.0
    - jinja2 <3.1
    - pyfiglet >=0.8.post1,<0.9
    - lightgbm >=3.3.2,<4.0.0
    - flaml >=1.0.11,<2.0.0
    - s3fs >=2022.8.2,<2023.0.0
    - sqlmodel >=0.0.19,<0.0.20
    - apscheduler >=3.9.1,<4.0.0
    - psycopg2-binary >=2.9.3,<3.0.0
    - analytics-python >=2.3.2,<3.0.0
    - python-dotenv >=0.21.0,<0.22.0
    - types-pyyaml >=6.0.12.8,<7.0
    - types-python-dateutil >=2.8.19.10,<3.0

test:
  imports:
    - nannyml
  commands:
    - pip check
    - nannyml --help
    - nml --help
  requires:
    - pip

about:
  home: https://github.com/nannyml/nannyml
  doc_url: https://nannyml.readthedocs.io/en/stable/
  summary: NannyML, Your library for monitoring model performance.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nnansters
    - thewchan
