github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
channels:
  sources:
    - conda-forge
    - defaults
    - sepandhaghighi
  targets:
    - ["conda-forge", "main"]
